superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('new/', views.create, name='create'),
    path('edit/<int:hero_id>/', views.edit, name='edit'),
    path('remove/<int:hero_id>/', views.remove, name='remove')

]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    edited_hero = Superhero.objects.get(pk=hero_id)
    if request.method == "POST":
        edited_hero.name = request.POST.get('name')
        edited_hero.alter_ego = request.POST.get('alter_ego')
        edited_hero.primary = request.POST.get('primary')
        edited_hero.secondary = request.POST.get('secondary')
        edited_hero.catchphrase = request.POST.get('catchphrase')
        edited_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        context = {
            'edited_hero': edited_hero
        }
        return render(request, 'superheroes/edit.html', context)

def remove(request, hero_id):
    removed_hero = Superhero.objects.get(pk=hero_id)
    removed_hero.delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add">
    </form>





</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Detail</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<body>
    <h1 align="center">Hero Details</h1>
    <table style="width: 25%" align="center">
        
        
        <h2 align="center"> {{single_hero.name}} </h2>
        <tr>
            <td align="center"><h3> Alter Ego: </h3></td>
            <td align="center"><h3> {{single_hero.alter_ego}} </h3></td>
        </tr>
        <tr>
            <td align="center"><h3> Primary Ability: </h3></td>
            <td align="center"><h3> {{single_hero.primary_ability}} </h3></td>
        </tr>
        <tr>
            <td align="center"><h3> Secondary Ability: </h3></td>
            <td align="center"><h3> {{single_hero.secondary_ability}} </h3></td>
        </tr>
        <tr>
            <td align="center"><h3> Catch Phrase: </h3></td>
            <td align="center"><h3> {{single_hero.catch_phrase}} </h3></td>
        </tr>
    </table>
        
        <h4 align="center"><a href="{% url 'superheroes:edit' single_hero.id %}">Edit</a></h4>
        <h4 align="center"><a href="{% url 'superheroes:remove' single_hero.id %}">Remove</a></h4>
        




</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
</head>
<body>
    
    
    <form action="{% url 'superheroes:edit' edited_hero.id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name" value="{{edited_hero.name}}"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego" value="{{edited_hero.alter_ego}}"><br />
        Primary Ability: <input type="text" name="primary" id="primary" value="{{edited_hero.primary_ability}}"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary" value="{{edited_hero.secondary_ability}}"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase" value="{{edited_hero.catch_phrase}}"><br />
        <input type="submit" value="Edit">
    </form>


</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<body>
{% load static %}
<img src = "{% static 'batman.jpg' %}" alt = "batman" width="500" height="750" style="float:left">
    <h1 align="center">List of Heroes</h1>
    <table style="width: 25%" align="center">
        {% for hero in all_heroes %}
        <tr>
        <td align="center"><h2> {{hero.name}} </h2></td>
        <td align="center"><h2> <a href="{% url 'superheroes:detail' hero.id %}">Details</a></h2></td>
        </tr>
        {% endfor %}
    </table>
    <h2 align="center"><a href="{% url 'superheroes:create' %}">Add New Hero</a></h2>
</body>
</html>